import type {
  PortalCompany,
  PortalDashboard,
  PortalDashboardEntitlement,
  PortalHelpArticle,
  PortalSubscription,
  PortalTeamInvite,
  PortalTeamMember,
  PortalTicket,
  PortalTicketMessage,
  PortalUsageAllowance,
  PortalUsageLog,
  PortalUser,
} from "@/lib/portal/types";

export const portalUsers: PortalUser[] = [
  {
    id: "user-maya",
    name: "Maya Hernandez",
    email: "maya@greenloopfoods.com",
    companyId: "company-greenloop",
    homeCompanyId: "company-greenloop",
    role: "client_admin",
    status: "active",
  },
  {
    id: "user-elliot",
    name: "Elliot Park",
    email: "elliot@greenloopfoods.com",
    companyId: "company-greenloop",
    homeCompanyId: "company-greenloop",
    role: "client_user",
    status: "active",
  },
  {
    id: "user-sam",
    name: "Sam Patel",
    email: "sam@ecofocusresearch.com",
    companyId: "company-ecofocus",
    homeCompanyId: "company-ecofocus",
    role: "support_admin",
    status: "active",
  },
];

export const portalTeamInvites: PortalTeamInvite[] = [
  {
    id: "invite-1",
    companyId: "company-greenloop",
    invitedUserId: "user-jordan",
    invitedName: "Jordan Lee",
    invitedEmail: "jordan@greenloopfoods.com",
    invitedRole: "client_user",
    invitedByUserId: "user-maya",
    inviteUrl: "https://portal.ecofocusresearch.com/set-password?email=jordan%40greenloopfoods.com&invite=1",
    deliveryStatus: "sent",
    deliveryMessage: null,
    createdAt: "2026-03-18T15:20:00Z",
    updatedAt: "2026-03-18T15:20:00Z",
    lastSentAt: "2026-03-18T15:20:00Z",
  },
];

export const portalCompanies: PortalCompany[] = [
  {
    id: "company-greenloop",
    name: "GreenLoop Foods",
    subscriptionId: "sub-greenloop",
    subscriberType: "brand",
    allowExternalCollaborators: false,
    externalAccessPolicy: null,
  },
  {
    id: "company-ecofocus",
    name: "EcoFocus Research",
    subscriptionId: "sub-ecofocus",
    subscriberType: "internal",
    allowExternalCollaborators: true,
    externalAccessPolicy: "support_admin_only",
  },
];

export const portalSubscriptions: PortalSubscription[] = [
  {
    id: "sub-greenloop",
    planName: "Enterprise Insight Suite",
    seatsPurchased: 12,
    seatsUsed: 8,
    renewalDate: "2026-08-15",
    status: "active",
  },
  {
    id: "sub-ecofocus",
    planName: "Internal Support Workspace",
    seatsPurchased: 20,
    seatsUsed: 9,
    renewalDate: "2026-12-31",
    status: "active",
  },
];

export const portalDashboards: PortalDashboard[] = [
  {
    id: "dashboard-eco-iq",
    slug: "eco-iq-overview",
    name: "EcoReputation™ Overview",
    description: "Topline sustainability perception trends, brand positioning, and audience shifts.",
    accessTag: "Included",
    embedUrl: null,
    embedAccess: "public_link",
  },
  {
    id: "dashboard-category",
    slug: "category-performance",
    name: "Category Performance",
    description: "Track category-level movement, segment filters, and quarterly benchmark changes.",
    accessTag: "Licensed",
    embedUrl: null,
    embedAccess: "displayr_login_required",
  },
  {
    id: "dashboard-2024-interactive",
    slug: "interactive-dashboard-2024",
    name: "2024 Interactive Dashboard",
    description: "Interactive Displayr dashboard for the 2024 study with page-level navigation, segment analysis, and export-ready views.",
    accessTag: "2024 Study",
    embedUrl: null,
    embedAccess: "public_link",
  },
  {
    id: "dashboard-export",
    slug: "export-readiness",
    name: "Export Readiness",
    description: "Download-oriented dashboard shell for chart and table extraction workflows.",
    accessTag: "Advanced",
    embedUrl: null,
    embedAccess: "displayr_login_required",
  },
  {
    id: "dashboard-custom",
    slug: "custom-client-study",
    name: "Custom Client Study",
    description: "Reserved for project-specific Displayr embeds and custom stakeholder views.",
    accessTag: "Project",
    embedUrl: null,
    embedAccess: "displayr_login_required",
  },
];

export const portalDashboardEntitlements: PortalDashboardEntitlement[] = [
  { companyId: "company-greenloop", dashboardId: "dashboard-eco-iq" },
  { companyId: "company-greenloop", dashboardId: "dashboard-category" },
  { companyId: "company-greenloop", dashboardId: "dashboard-2024-interactive" },
  { userId: "user-maya", dashboardId: "dashboard-export" },
  { userId: "user-maya", dashboardId: "dashboard-custom" },
  { companyId: "company-ecofocus", dashboardId: "dashboard-eco-iq" },
  { companyId: "company-ecofocus", dashboardId: "dashboard-category" },
  { companyId: "company-ecofocus", dashboardId: "dashboard-2024-interactive" },
  { companyId: "company-ecofocus", dashboardId: "dashboard-export" },
  { companyId: "company-ecofocus", dashboardId: "dashboard-custom" },
];

export const portalUsageAllowances: PortalUsageAllowance[] = [
  {
    companyId: "company-greenloop",
    annualHoursLimit: 120,
    hoursUsed: 92,
    periodStart: "2026-01-01",
    periodEnd: "2026-12-31",
  },
];

export const portalUsageLogs: PortalUsageLog[] = [
  {
    id: "usage-1",
    userId: "user-maya",
    companyId: "company-greenloop",
    workspaceCompanyId: "company-greenloop",
    billingCompanyId: "company-greenloop",
    userHomeCompanyId: "company-greenloop",
    dashboardId: "dashboard-eco-iq",
    dashboardName: "EcoReputation™ Overview",
    eventType: "viewer_session",
    eventAt: "2026-03-08T15:10:00Z",
    minutesTracked: 32,
    source: "mock",
    notes: "Quarterly leadership review session.",
  },
  {
    id: "usage-2",
    userId: "user-maya",
    companyId: "company-greenloop",
    workspaceCompanyId: "company-greenloop",
    billingCompanyId: "company-greenloop",
    userHomeCompanyId: "company-greenloop",
    dashboardId: "dashboard-2024-interactive",
    dashboardName: "2024 Interactive Dashboard",
    eventType: "viewer_session",
    eventAt: "2026-03-09T13:45:00Z",
    minutesTracked: 48,
    source: "mock",
    notes: "Interactive segment analysis review.",
  },
  {
    id: "usage-3",
    userId: "user-elliot",
    companyId: "company-greenloop",
    workspaceCompanyId: "company-greenloop",
    billingCompanyId: "company-greenloop",
    userHomeCompanyId: "company-greenloop",
    dashboardId: "dashboard-2024-interactive",
    dashboardName: "2024 Interactive Dashboard",
    eventType: "viewer_session",
    eventAt: "2026-03-09T17:20:00Z",
    minutesTracked: 18,
    source: "mock",
    notes: "Client prep session.",
  },
  {
    id: "usage-4",
    userId: "user-elliot",
    companyId: "company-greenloop",
    workspaceCompanyId: "company-greenloop",
    billingCompanyId: "company-greenloop",
    userHomeCompanyId: "company-greenloop",
    dashboardId: "dashboard-2024-interactive",
    dashboardName: "2024 Interactive Dashboard",
    eventType: "allowance_override",
    eventAt: "2026-03-10T09:00:00Z",
    minutesTracked: 0,
    source: "mock",
    notes: "Temporary manual allowance adjustment recorded for review.",
  },
];

export const portalTickets: PortalTicket[] = [
  {
    id: "TCK-1042",
    companyId: "company-greenloop",
    subject: "Exported chart labels are truncating in PNG output",
    dashboardName: "Category Performance",
    issueType: "Chart Export",
    priority: "high",
    status: "in_progress",
    createdAt: "2026-03-04T14:22:00Z",
    updatedAt: "2026-03-09T18:40:00Z",
    requesterId: "user-maya",
    ownerId: "user-sam",
  },
  {
    id: "TCK-1038",
    companyId: "company-greenloop",
    subject: "Need segment filter guidance for leadership review",
    dashboardName: "EcoReputation™ Overview",
    issueType: "Training Request",
    priority: "medium",
    status: "waiting_on_client",
    createdAt: "2026-02-27T10:18:00Z",
    updatedAt: "2026-03-08T16:05:00Z",
    requesterId: "user-maya",
    ownerId: "user-sam",
  },
  {
    id: "TCK-1031",
    companyId: "company-greenloop",
    subject: "Can’t access project dashboard after seat reassignment",
    dashboardName: "Custom Client Study",
    issueType: "Login / Access",
    priority: "urgent",
    status: "open",
    createdAt: "2026-03-09T08:50:00Z",
    updatedAt: "2026-03-09T08:50:00Z",
    requesterId: "user-elliot",
    ownerId: null,
  },
];

export const portalTicketMessages: PortalTicketMessage[] = [
  {
    id: "msg-1",
    ticketId: "TCK-1042",
    authorId: "user-maya",
    body: "The export looks correct in the dashboard preview, but the downloaded PNG cuts off long axis labels.",
    createdAt: "2026-03-04T14:22:00Z",
    isInternal: false,
  },
  {
    id: "msg-2",
    ticketId: "TCK-1042",
    authorId: "user-sam",
    body: "We reproduced this with narrow viewport exports and are reviewing the chart container sizing.",
    createdAt: "2026-03-05T09:10:00Z",
    isInternal: false,
  },
  {
    id: "msg-3",
    ticketId: "TCK-1042",
    authorId: "user-sam",
    body: "Internal note: likely needs a Displayr export preset tied to the category dashboard theme.",
    createdAt: "2026-03-05T09:22:00Z",
    isInternal: true,
  },
  {
    id: "msg-4",
    ticketId: "TCK-1038",
    authorId: "user-maya",
    body: "We want to understand which segment filters to apply before exporting a leadership-ready story deck.",
    createdAt: "2026-02-27T10:18:00Z",
    isInternal: false,
  },
  {
    id: "msg-5",
    ticketId: "TCK-1038",
    authorId: "user-sam",
    body: "Shared a recommended workflow. Waiting on confirmation of which stakeholder audience the deck targets.",
    createdAt: "2026-03-08T16:05:00Z",
    isInternal: false,
  },
  {
    id: "msg-6",
    ticketId: "TCK-1031",
    authorId: "user-elliot",
    body: "I was removed and re-added to the project team last week. The custom study dashboard now shows no access.",
    createdAt: "2026-03-09T08:50:00Z",
    isInternal: false,
  },
];

export const portalHelpArticles: PortalHelpArticle[] = [
  {
    id: "article-login",
    slug: "logging-in-to-the-portal",
    title: "Logging in to the EcoFocus portal",
    category: "Access",
    summary: "Use your work email to receive a secure sign-in link and return to your assigned portal workspace.",
    content:
      "Use your approved work email to sign in to the EcoFocus portal. Access is tied to your company account, seat assignment, and dashboard entitlements.\n\nIf you are a returning user, start from the portal login page and use the same work email your organization registered for portal access. After authentication, you will be returned to your private workspace and will only see dashboards, support tools, and account features available to your role.\n\nIf you do not see the dashboards you expected, first confirm that you are using the correct work email and company account. If access still looks incomplete, contact your internal portal administrator or EcoFocus Support so we can review your account configuration, seat assignment, and dashboard mapping.",
  },
  {
    id: "article-exporting",
    slug: "exporting-charts-and-tables",
    title: "Exporting charts and tables",
    category: "Exports",
    summary: "Best practices for PNG, PPT, and table exports from Displayr-based dashboard views.",
    content:
      "Before exporting, apply the exact filters and cuts you want reflected in the final output. Exported charts and tables reflect the current view, so it is important to confirm your segment selection, date range, and comparison state before downloading anything.\n\nFor presentation-ready outputs, check the chart title, legend, and axis labels before export. If you are building a leadership deck, capture a screenshot of the configured view so your team can trace the exported output back to the dashboard state used to generate it.\n\nIf labels are truncated or a table export does not match the view on screen, note the dashboard name, page, export type, and the filters in use. Include those details in a support request so EcoFocus can reproduce the issue quickly.",
  },
  {
    id: "article-eco-iq",
    slug: "understanding-eco-iq",
    title: "Understanding EcoReputation™",
    category: "Metrics",
    summary: "How to interpret EcoReputation™ scoring, benchmark ranges, and movement over time.",
    content:
      "EcoReputation™ is a directional metric designed to help teams understand how audiences respond to sustainability positioning, trust signals, and related perception indicators over time. It is most useful when viewed alongside the benchmark context and the audience definition behind the score.\n\nWhen comparing EcoReputation™ across brands, segments, or reporting periods, always confirm that you are working from a comparable base. A movement in score can reflect real audience change, but it can also reflect a different segment mix, a narrower sample, or a different reporting lens.\n\nUse EcoReputation™ as the starting point for interpretation, not the end point. Once you identify movement, drill into the supporting cuts and related charts to understand which audience groups, themes, or perception drivers are contributing to the change.",
  },
  {
    id: "article-segments",
    slug: "filtering-segments",
    title: "Filtering segments effectively",
    category: "Analysis",
    summary: "How to use segment filters without introducing conflicting cuts into stakeholder-ready outputs.",
    content:
      "Start with one primary segment dimension and confirm the sample before layering in additional cuts. The clearest reporting stories usually come from a well-defined first cut rather than a heavily filtered view that becomes difficult to explain later.\n\nIf you need compound filtering, document it clearly. Teams often lose confidence in exports when the audience definition is not obvious from the chart alone. Keep a short note on the segment logic used for important exports so the same definitions can be reused across stakeholder reviews.\n\nIf you are preparing a client-facing or executive-ready output, validate the filtered view one more time before exporting. This helps avoid situations where a previous exploratory filter is still active and changes the interpretation of the final output.",
  },
  {
    id: "article-downloads",
    slug: "downloading-data-tables",
    title: "Downloading data tables",
    category: "Exports",
    summary: "Where to find table downloads and how to request a custom extract if the standard export is not sufficient.",
    content:
      "Use the dashboard utility controls to review the available table download options for the current page or view. Standard table downloads are best for quick reviews, recurring internal reporting, and validation checks against the charts shown in the dashboard.\n\nIf you need a more specific extract, define the exact output before submitting a request. Include the dashboard name, page, target audience cut, fields needed, and the preferred delivery format. The more precise the request, the faster EcoFocus can confirm whether the standard export covers it or whether a custom extract is needed.\n\nWhen requesting a custom table, explain how the output will be used. That helps us determine whether you need a dashboard export, a one-time data pull, or a more structured deliverable.",
  },
];

export const portalTeamMembers: PortalTeamMember[] = [
  {
    id: "team-1",
    companyId: "company-greenloop",
    homeCompanyId: "company-greenloop",
    homeCompanyName: "GreenLoop Foods",
    name: "Maya Hernandez",
    email: "maya@greenloopfoods.com",
    role: "client_admin",
    status: "active",
  },
  {
    id: "team-2",
    companyId: "company-greenloop",
    homeCompanyId: "company-greenloop",
    homeCompanyName: "GreenLoop Foods",
    name: "Elliot Park",
    email: "elliot@greenloopfoods.com",
    role: "client_user",
    status: "active",
  },
  {
    id: "team-3",
    companyId: "company-greenloop",
    homeCompanyId: "company-greenloop",
    homeCompanyName: "GreenLoop Foods",
    name: "Jordan Lee",
    email: "jordan@greenloopfoods.com",
    role: "client_user",
    status: "invited",
  },
];
